name: Automated Tests 
on: [push]
jobs: 
  test_find_lowest_number_file:
    name: Automated Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
                  python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
                  python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
                  python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
  
  

      - name: Compare the output 
        run: |
                  diff -Z test_data/test1_output.txt test_data/test1_expected.txt
                  diff -Z test_data/test2_output.txt test_data/test2_expected.txt
                  diff -Z test_data/test3_output.txt test_data/test3_expected.txt
  

               
            
          
